services:
  - type: web
    name: vidmind-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: OPENAI_API_KEY
        sync: false
      - key: LANGSMITH_API_KEY
        sync: false
      - key: LANGSMITH_TRACING
        value: "true"
      - key: LANGSMITH_PROJECT
        value: "VidMind-AI"
      - key: LANGCHAIN_TRACING_V2
        value: "true"
      - key: LANGCHAIN_PROJECT
        value: "VidMind-AI"
